### ISSUE TITLE
undefined method `slice' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by akekho** [habemus-papadum/kernel-grok#2]
```bash
../kernel-grok/generate_cmake:45:in `block (2 levels) in <main>': undefined method `slice' for nil:NilClass (NoMethodError)
	from ../kernel-grok/generate_cmake:40:in `each'
	from ../kernel-grok/generate_cmake:40:in `block in <main>'
	from ../kernel-grok/generate_cmake:30:in `open'
	from ../kernel-grok/generate_cmake:30:in `<main>'
```

**Comment by habemus-papadum** [comment]
can you post your `compilation_commands.json` and the intercepted make command you use to build the kernel?

**Comment by akekho** [comment]
Sorry for the late reply. I have deleted my VPS instance and I din't back up the file. So I can't provide the `compilation_commands.json` now. I will reopen the issue when I reproduce the problem. Thanks anyway.
